title: "UCSB CS Transfer Student Resources"
github_url: "https://github.com/ucsb-cs-transfer-resources/ucsb-cs-transfer-resources.github.io"

#kramdown:
#  parse_block_html: true

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/

  resources:
    output: true
    permalink: /resources/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: topic

  - scope:
      path: ""
      type: resources
    values:
      layout: topic
